package com.tianqizhang.webapp.dynamodb.Models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.security.SecureRandom;
import java.util.Base64;

@DynamoDBTable(tableName = "dynamodb-table")
public class DynamodbUser {

    private static final SecureRandom secureRandom = new SecureRandom(); //threadsafe
    private static final Base64.Encoder base64Encoder = Base64.getUrlEncoder(); //threadsafe

    public static String generateNewToken() {
        byte[] randomBytes = new byte[24];
        secureRandom.nextBytes(randomBytes);
        return base64Encoder.encodeToString(randomBytes);
    }

    public DynamodbUser(String user_email) {
        this.user_email = user_email;
        this.token = generateNewToken();
        this.expirationTime = System.currentTimeMillis() + 5 * 60 * 1000;
        this.used = false;
    }

    public String getUser_email() {
        return user_email;
    }

    public void setUser_email(String user_email) {
        this.user_email = user_email;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public long getExpirationTime() {
        return expirationTime;
    }

    public void setExpirationTime(long expirationTime) {
        this.expirationTime = expirationTime;
    }

    public Boolean getUsed() {
        return used;
    }

    public void setUsed(Boolean used) {
        this.used = used;
    }

    @DynamoDBHashKey(attributeName = "user_email")
    private String user_email;

    @DynamoDBAttribute(attributeName = "token")
    private String token;

    @DynamoDBAttribute(attributeName = "expirationTime")
    private long expirationTime;

    @DynamoDBAttribute(attributeName = "used")
    private Boolean used;
}
